### ISSUE TITLE
Roles instead of hasPermissions?

### ISSUE THREAD

**Issue by Bloodmorphed** [dragonfire535/discord.js-commando-beginners-guide#4]
Has permissions (in my opinion), is kind of bad. While this isn't an issue, and more of a question... can you check for a role instead of a permission? Because there are certain times you want users to have certain roles, and absolutely no permissions for the server itself. So you either have to try to figure out which permission to give one role and higher. And that is just inefficient, I think.

**Comment by DevYukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
