### ISSUE TITLE
SQLite Provider section does not work. I get a promise rejection

### ISSUE THREAD

**Issue by Bloodmorphed** [dragonfire535/discord.js-commando-beginners-guide#5]
`(node:8470) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SQLITE_CANTOPEN: unable to open database file
`

Here is the code I have:

```
const sqlite = require('sqlite');
const { CommandoClient, SQLiteProvider } = require('discord.js-commando');
const path = require('path');
const bot = new CommandoClient({
  commandPrefix: config.prefix,
  owner: config.owner,
  unknownCommandResponse: false,
});

// SQL Priver
sqlite.open(path.join(__dirname, 'settings.sqlite3')).then((db) => {
  bot.setProvider(new SQLiteProvider(db));
});
```

**Comment by Gawdl3y** [comment]
This is not an issue with Commando or the guide, and your question should be taken to the SQLite/SQLite3 libs. My guess, though, is you don't have permission to write the file there, or there is already a file there in the improper format.
